<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <div class="btn-toolbar">
        <div class="dropdown">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?>
          </button>

          <div class="dropdown-menu">
             <a class="dropdown-item" href="<?php echo $this->url('Tour:Admin:Booking@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('New booking'); ?></a>
             <div class="dropdown-divider"></div>
             <div class="dropdown-header"><?php $this->show('Actions'); ?></div>

             <?php if (!empty($bookings)): ?>
             <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Tour:Admin:Booking@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
             <?php else: ?>
             <a class="dropdown-item"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>         
             <?php endif; ?>
          </div>
        </div>
    </div>

    <?php $this->loadPartial('items-per-page', array('caption' => 'Bookings')); ?>

    <form autocomplete="off">
        <?= $this->widget(new GridViewWidget($bookings, array(
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'rowAttributes' => array(
                'class' => function($row){
                    if ($row['status'] == -1) {
                        return 'danger';
                    }
                }
            ),
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'tour',
                ),

                array(
                    'column' => 'client',
                ),

                array(
                    'column' => 'email',
                ),

                array(
                    'column' => 'phone',
                ),
                
                array(
                    'column' => 'datetime',
                    'label' => 'Date and time'
                ),

                array(
                    'column' => 'amount',
                    'label' => 'Price'
                )
            ),

            'actions' => array(
                'notify' => function($row){
                    // Don't let
                    if ($row['amount'] == 0) {
                        return null;
                    }

                    return Icon::button('glyphicon glyphicon-envelope', $this->url('Tour:Admin:Booking@notifyAction', $row['token']), $this->translate('Send invoice to their email'));
                },

                'edit' => function($row){
                    return Icon::edit(
                        $this->url('Tour:Admin:Booking@editAction', $row['id']),
                        $this->translate('Edit this booking')
                    );
                },

                'remove' => function($row){
                    return Icon::remove(
                        $this->url('Tour:Admin:Booking@deleteAction', $row['id']),
                        $this->translate('Delete this booking')
                    );
                }
            )
        ))); ?>

    </form>

    <?php $this->loadPartial('paginator'); ?>

</div>