<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="category" autocomplete="off">
	<ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="#page" data-toggle="tab"><i class="fas fa-folder-open"></i> <?= $this->translate('Category'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#configuration" data-toggle="tab"><i class="fas fa-tasks"></i> <?= $this->translate('Configuration'); ?></a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="page">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade show <?= $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $category); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Category name')]); ?>
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>

                    <div class="options">
                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), ['class' => 'form-control', 'placeholder' => $this->translate('URL slug for this category. By default is taken from the name')]); ?>

                                    <div class="input-group-append">
                                        <a class="input-group-text" href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="bi bi-arrow-clockwise" data-toggle="tooltip" title="<?= $this->translate('Refresh the slug'); ?>"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), ['class' => 'form-control']); ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), ['class' => 'form-control']); ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate("Category title")]); ?>
                                    <div class="input-group-append">
                                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_keywords]', $language->getId()), $entity->getMetaKeywords(), ['class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines')]); ?>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), ['class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines')]); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

            <?php $this->loadPartial('actions', [
                'new' => !$entity->getId(),
                'add' => 'Tour:Admin:Category@addAction',
                'edit' => 'Tour:Admin:Category@editAction',
                'save' => 'Tour:Admin:Category@saveAction',
                'cancel' => 'Tour:Admin:Grid@indexAction',
                'options' => true
            ]); ?>

		</div>

        <div class="tab-pane" id="configuration">
            <?= Element::hidden('category[id]', $entity->getId()); ?>
            <?= Element::hidden('category[cover]', $entity->getCover()); ?>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Image'); ?></label>
                <div class="col-lg-10">
                    <p>
                        <img data-image="<?= $entity->getId() ? null : 'preview'; ?>" src="<?= $entity->getImageUrl('400x400'); ?>" />
                    </p>

                    <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="bi bi-image"></i> <?= $this->translate('Upload a file'); ?></a>
                    <?= Element::file('file', 'image/x-png, image/gif, image/jpeg', ['class' => 'hidden', 'data-plugin' => 'preview']); ?>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Enable SEO'); ?></label>
                <div class="col-lg-10">
                    <?= Element::checkbox('category[seo]', $entity->getSeo(), ['class' => 'form-control']) ?>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Order'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('category[order]', $entity->getOrder(), ['class' => 'form-control', 'min' => 0]) ?>
                </div>
            </div>
        </div>
	</div>
</form>