<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form autocomplete="off" action="<?= $route; ?>">
    <div class="dropdown">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <?php if ($newReviews > 0): ?>(<?= $newReviews; ?>)<?php endif; ?>
      </button>

      <div class="dropdown-menu">
         <a class="dropdown-item" href="<?php echo $this->url('Tour:Admin:Tour@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add a tour'); ?></a>
         <a class="dropdown-item" href="<?php echo $this->url('Tour:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Add category'); ?></a>
         <a class="dropdown-item" href="<?php echo $this->url('Tour:Admin:Booking@indexAction', null); ?>"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Bookings'); ?></a>
         <a class="dropdown-item" href="<?php echo $this->url('Tour:Admin:TourDestination@indexAction'); ?>"><i class="glyphicon glyphicon-resize-small"></i> <?php $this->show('Tour destinations'); ?></a>
         <a class="dropdown-item" href="<?php echo $this->url('Tour:Admin:TourReview@indexAction', null); ?>">
            <?php if ($newReviews == 0): ?>
            <?php $this->show('Reviews'); ?></a>
            <?php else: ?>
            <span class="text-danger"><i class="glyphicon glyphicon-comment"></i> <?php $this->show('Reviews'); ?> (<?= $newReviews; ?>)</span>
            <?php endif; ?>
         </a>
         <div class="dropdown-divider"></div>
         <div class="dropdown-header"><?php $this->show('Actions'); ?></div>
         <?php if (!empty($tours)): ?>
         <a class="dropdown-item" href="#" data-button="remove-selected" data-url="<?php echo $this->url('Tour:Admin:Tour@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>
         <?php else: ?>
         <a class="class="dropdown-item""><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a>         
         <?php endif; ?>
      </div>
    </div>

    <button class="btn btn-primary" type="submit"><?php $this->show('Filter'); ?></button>

    <div class="card">
        <?php $this->loadPartial('items-per-page', array('caption' => 'Tours')); ?>

        <?= $this->widget(new GridViewWidget($tours, array(
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                    'filter' => true
                ),

                array(
                    'column' => 'category',
                    'name' => 'category_id',
                    'type' => 'select',
                    'filter' => $categoryList
                ),

                array(
                    'column' => 'adults',
                    'filter' => true,
                    'label' => 'Number of adults'
                ),

                array(
                    'column' => 'order'
                ),

                array(
                    'column' => 'published',
                    'type' => 'select',
                    'filter' => 'boolean',
                    'translateable' => true,
                    'value' => function($row){
                        return $row['published'] ? 'Yes' : 'No';
                    }
                )
            ),

            'actions' => array(
                'view' => function($row){
                    return Icon::view($row->getUrl(), $this->translate('View this tour on site'));
                },

                'edit' => function($row){
                    return Icon::edit(
                        $this->url('Tour:Admin:Tour@editAction', $row['id']),
                        $this->translate('Edit this tour')
                    );
                },

                'remove' => function($row){
                    return Icon::remove(
                        $this->url('Tour:Admin:Tour@deleteAction', $row['id']),
                        $this->translate('Remove this tour')
                    );
                }
            )

        ), $route)); ?>

        <?php if (empty($tours)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No tours'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

    <div class="card">
        <h2><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Categories'); ?> <small>(<?php echo count($categories); ?>)</small></h2>

        <?= $this->widget(new GridViewWidget($categories, array(
            'pk' => 'id',
            'batch' => false,
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                ),

                array(
                    'column' => 'tour_count'
                )
            ),

            'actions' => array(
                'view' => function($row){
                    return Icon::view($row->getUrl(), $this->translate('View this category on site'));
                },

                'edit' => function($row){
                    return Icon::edit($this->url('Tour:Admin:Category@editAction', $row['id']), $this->translate('Edit this category'));
                },

                'remove' => function($row){
                    return Icon::remove($this->url('Tour:Admin:Category@deleteAction', $row['id']), $this->translate('Remove this category'));
                }
            )
        ))); ?>

        <?php if (empty($categories)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

</form>
