<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form autocomplete="off" action="<?= $route; ?>">
    <div class="btn-toolbar">
        <div class="btn-group mr-2">
            <?php $this->loadPartial('menu', array(
                'notifications' => $newReviews,
                'items' => array(
                    'Tour:Admin:Tour@addAction' => 'Add a tour',
                    'Tour:Admin:Category@addAction' => 'Add category',
                    'Tour:Admin:Booking@indexAction' => 'Bookings',
                    'Tour:Admin:TourDestination@indexAction' => 'Tour destinations',
                    'Tour:Admin:TourReview@indexAction' => array(
                        'caption' => 'Reviews',
                        'notifications' => $newReviews
                    )
                ),

                'actions' => array(
                    'data' => $tours,
                    'delete' => 'Tour:Admin:Tour@deleteAction'
                )
            )); ?>
        </div>

        <div class="btn-group mr-2">
            <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i> <?php $this->show('Filter'); ?></button>
        </div>
    </div>

    <div class="card">
        <?php $this->loadPartial('items-per-page', array('caption' => 'Tours')); ?>

        <?= $this->widget(new GridViewWidget($tours, array(
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                    'filter' => true
                ),

                array(
                    'column' => 'category',
                    'name' => 'category_id',
                    'type' => 'select',
                    'filter' => $categoryList
                ),

                array(
                    'column' => 'adults',
                    'filter' => true,
                    'label' => 'Number of adults'
                ),

                array(
                    'column' => 'order'
                ),

                array(
                    'column' => 'published',
                    'type' => 'select',
                    'filter' => 'boolean',
                    'translateable' => true,
                    'value' => function($row){
                        return $row['published'] ? 'Yes' : 'No';
                    }
                )
            ),

            'actions' => array(
                'view' => function($row){
                    return Icon::view($row->getUrl(), $this->translate('View this tour on site'));
                },

                'edit' => function($row){
                    return Icon::edit(
                        $this->url('Tour:Admin:Tour@editAction', $row['id']),
                        $this->translate('Edit this tour')
                    );
                },

                'remove' => function($row){
                    return Icon::remove(
                        $this->url('Tour:Admin:Tour@deleteAction', $row['id']),
                        $this->translate('Remove this tour')
                    );
                }
            )

        ), $route)); ?>

        <?php if (empty($tours)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No tours'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

    <div class="card">
        <h2><i class="glyphicon glyphicon-folder-open"></i> <?php $this->show('Categories'); ?> <small>(<?php echo count($categories); ?>)</small></h2>

        <?= $this->widget(new GridViewWidget($categories, array(
            'pk' => 'id',
            'batch' => false,
            'tableClass' => 'table table-hover table-bordered table-striped',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                ),

                array(
                    'column' => 'tour_count'
                )
            ),

            'actions' => array(
                'view' => function($row){
                    return Icon::view($row->getUrl(), $this->translate('View this category on site'));
                },

                'edit' => function($row){
                    return Icon::edit($this->url('Tour:Admin:Category@editAction', $row['id']), $this->translate('Edit this category'));
                },

                'remove' => function($row){
                    return Icon::remove($this->url('Tour:Admin:Category@deleteAction', $row['id']), $this->translate('Remove this category'));
                }
            )
        ))); ?>

        <?php if (empty($categories)): ?>
        <div class="center-block">
            <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No categories'); ?></h2>
        </div>
        <?php endif; ?>
    </div>

</form>
