<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

?>

<div class="card card-body">
    <?php $this->loadPartial('items-per-page', ['caption' => 'Reviews']); ?>

    <?= $this->widget(new GridViewWidget($reviews, [
        'pk' => 'id',
        'batch' => true,
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => [
            'class' => function($row){
                if ($row['published'] == 0){
                    return 'table-danger';
                }
            }
        ],
        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'tour',
            ],

            [
                'column' => 'datetime',
                'label' => 'Date and time'
            ],

            [
                'column' => 'name',
            ],

            [
                'column' => 'message',
            ]
        ],

        'actions' => [
            function($entity){
                if ($entity['published'] == 0){
                    return Icon::approve(
                        $this->url('Tour:Admin:TourReview@approveAction', $entity['id']),
                        $this->translate('Approve this review')
                    );
                }
            },

            function($row){
                return Icon::remove(
                    $this->url('Tour:Admin:TourReview@deleteAction', $row['id']),
                    $this->translate('Remove this review')
                );
            }
        ]
    ])); ?>

</div>