<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <?php $this->loadPartial('items-per-page', array('caption' => 'Reviews')); ?>

    <?= $this->widget(new GridViewWidget($reviews, array(
        'pk' => 'id',
        'batch' => true,
        'tableClass' => 'table table-hover table-bordered table-striped',
        'rowAttributes' => array(
            'class' => function($row){
                if ($row['published'] == 0){
                    return 'danger';
                }
            }
        ),
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'tour',
            ),

            array(
                'column' => 'datetime',
                'label' => 'Date and time'
            ),

            array(
                'column' => 'name',
            ),

            array(
                'column' => 'message',
            )
        ),

        'actions' => array(
            'approve' => function($entity){
                if ($entity['published'] == 0){
                    return Icon::approve(
                        $this->url('Tour:Admin:TourReview@approveAction', $entity['id']),
                        $this->translate('Approve this review')
                    );
                }
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Tour:Admin:TourReview@deleteAction', $row['id']),
                    $this->translate('Remove this review')
                );
            }
        )
    ))); ?>

</div>