<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

defined('KRYSTAL') or die;

?>

<?php $this->loadPartial('items-per-page', array('caption' => 'Reviews')); ?>

<?= Grid::render($reviews, array(
    // A column to be considered as a primary key
    'pk' => 'id',
    'batch' => true,
    'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
    'rowAttributes' => array(
        'class' => function($row){
            if ($row['published'] == 0){
                return 'danger';
            }
        }
    ),
    'columns' => array(
        array(
            'column' => 'id',
            'label' => '#'
        ),

        array(
            'column' => 'tour',
        ),

        array(
            'column' => 'datetime',
            'label' => 'Date and time'
        ),

        array(
            'column' => 'name',
        ),

        array(
            'column' => 'message',
        )
    ),

    'actions' => array(
        'approve' => function($entity){
            if ($entity['published'] == 0){
                $url = $this->url('Tour:Admin:TourReview@approveAction', $entity['id']);

                return Element::icon('glyphicon glyphicon-check', $url, array(
                    'data-toggle' => 'tooltip',
                    'data-placement' => 'left',
                    'data-original-title' => $this->translate('Approve this review')
                ));
            }
        },

        'remove' => function($row){
            return Element::icon('glyphicon glyphicon-remove', '#', array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Remove this review'), 'data-button' => 'delete', 'data-url' => $this->url('Tour:Admin:TourReview@deleteAction', $row['id'])));
        }
    )

), $this->translator); ?>
