<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <a class="btn btn-primary btn-sm" href="<?= $this->url('Tour:Admin:TourDestination@addAction'); ?>"><i class="glyphicon glyphicon-resize-small"></i> <?php $this->show('Add new tour destination'); ?></a>
</div>

<div class="card">
    <h2 class="page-header"><i class="glyphicon glyphicon-resize-small"></i> <?php $this->show('Tour destinations'); ?> <small>(<?= count($destinations); ?>)</small></h2>

    <?= $this->widget(new GridViewWidget($destinations, array(
        'pk' => 'id',
        'tableClass' => 'table table-hover table-bordered table-striped',
        'columns' => array(
            array(
                'column' => 'id',
                'label' => '#'
            ),

            array(
                'column' => 'name',
            ),

            array(
                'column' => 'order',
            )
        ),

        'actions' => array(
            'edit' => function($row){
                return Icon::edit(
                    $this->url('Tour:Admin:TourDestination@editAction', $row['id']),
                    $this->translate('Edit this destination')
                );
            },

            'remove' => function($row){
                return Icon::remove(
                    $this->url('Tour:Admin:TourDestination@deleteAction', $row['id']),
                    $this->translate('Remove this destination')
                );
            }
        )
    ))); ?>

    <?php if (empty($destinations)): ?>
    <div class="center-block">
        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No tour destinations'); ?></h2>
    </div>
    <?php endif; ?>

</div>