<?php

use Krystal\Form\Element;

?>

<form class="card card-body" autocomplete="off">
    <?= Element::hidden('image[id]', $image->getId()); ?>
    <?= Element::hidden('image[image]', $image->getImage()); ?>
    <?= Element::hidden('image[tour_id]', $image->getTourId()); ?>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Image'); ?></label>
        <div class="col-lg-10">
            <p>
                <img data-image="<?= $image->getId() ? null : 'preview'; ?>" src="<?= $image->getImageUrl('400x400'); ?>" />
            </p>

            <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="bi bi-image"></i> <?= $this->translate('Upload a file'); ?></a>
            <?= Element::file('file', 'image/x-png, image/gif, image/jpeg', ['class' => 'd-none', 'data-plugin' => 'preview']); ?>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Order'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('image[order]', $image->getOrder(), ['class' => 'form-control', 'placeholder' => $this->translate('Sorting order')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$image->getId(),
        'add' => ['Tour:Admin:TourGallery@addAction', $image->getTourId()],
        'edit' => 'Tour:Admin:TourGallery@editAction',
        'save' => 'Tour:Admin:TourGallery@saveAction',
        'cancel' => ['Tour:Admin:Tour@editAction', $image->getTourId()]
    ]); ?>

</form>