<?php

use Krystal\Form\Element;
use Krystal\Grid\Grid;
use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form data-group="category">
	<ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Tour'); ?></a></li>
        <li role="presentation"><a href="#days" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Days'); ?></a></li>
        <li role="presentation"><a href="#gallery" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Gallery'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="page" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $tour); ?>

                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('What\'s included'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][included]', $language->getId()), $entity->getIncluded(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('What\'s not included'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][excluded]', $language->getId()), $entity->getExcluded(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="options">
                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this category. By default is taken from a title'))); ?>
                                        <span class="input-group-addon">
                                            <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate("Category title"))); ?>
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][meta_keywords]', $language->getId()), $entity->getMetaKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
			</div>

            <?php if ($entity->getId()):?>
			<button data-button="save" data-url="<?php echo $this->url('Tour:Admin:Tour@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
            <button data-button="save-create" data-back-url="<?php echo $this->url('Tour:Admin:Tour@addAction'); ?>" data-url="<?php echo $this->url('Tour:Admin:Tour@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>

            <?php else: ?>
            <button data-button="add" data-back-url="<?php echo $this->url('Tour:Admin:Tour@editAction', null); ?>" data-url="<?php echo $this->url('Tour:Admin:Tour@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
            <button data-button="add-create" data-url="<?php echo $this->url('Tour:Admin:Tour@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Add & Create new'); ?></button>

			<?php endif; ?>
            <button data-button="options" class="btn btn-primary"><i class="glyphicon glyphicon-open"></i> <?php $this->show('More options'); ?></button>
            <button data-button="cancel" data-url="<?php echo $this->url('Tour:Admin:Grid@indexAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-open"></i> <?php $this->show('Cancel'); ?></button>
		</div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <div class="well">
                <?php echo Element::hidden('tour[id]', $entity->getId()); ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Categories'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('categories[]', $categories, $entity->getCategoryIds(), array('class' => 'form-control', 'multiple' => true, 'data-plugin' => 'chosen')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Related tours'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('related[]', $tours, $entity->getRelatedIds(), array('class' => 'form-control', 'multiple' => true, 'data-plugin' => 'chosen')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('tour[seo]', $entity->getSeo(), array('class' => 'form-control')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Recommended'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('tour[recommended]', $entity->getRecommended(), array('class' => 'form-control')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('tour[published]', $entity->getPublished(), array('class' => 'form-control')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[order]', $entity->getOrder(), array('class' => 'form-control', 'min' => 0)) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Number of adults'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[adults]', $entity->getAdults(), array('class' => 'form-control', 'min' => 0)) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Number of children'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[children]', $entity->getChildren(), array('class' => 'form-control', 'min' => 0)) ?>
                    </div>
                </div>
            </div>
        </div>
        
        <div role="tabpanel" class="tab-pane" id="days">
            <div class="well">
                <p>
                    <a class="btn btn-primary" href="<?php echo $this->url('Tour:Admin:TourDay@addAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-retweet"></i> <?php $this->show('Add new day'); ?></a>
                </p>

                <?php echo Grid::render($days, array(
                    'pk' => 'id',
                    'columns' => array(
                        array(
                            'column' => 'id',
                            'label' => '#'
                        ),
                        array(
                            'column' => 'title'
                        ),
                        array(
                            'column' => 'order'
                        )
                    ),
                    'actions' => array(
                        'edit' => function($entity){
                            return Element::icon('glyphicon glyphicon-pencil', $this->url('Tour:Admin:TourDay@editAction', $entity['id']));
                        },
                        'delete' => function($entity){
                            // Generate URL
                            $url = $this->url('Tour:Admin:TourDay@deleteAction', $entity['id']);
                            return Element::icon('glyphicon glyphicon-remove', '#', array('data-button' => 'delete', 'data-url' => $url));
                        }
                    )
                ), $this->translator); ?>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane" id="gallery">
            <div class="well">
                <p>
                    <a class="btn btn-primary" href="<?php echo $this->url('Tour:Admin:TourGallery@addAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-retweet"></i> <?php $this->show('Add new image'); ?></a>
                </p>

                <?php echo Grid::render($gallery, array(
                    'pk' => 'id',
                    'columns' => array(
                        array(
                            'column' => 'id',
                            'label' => '#'
                        ),
                        array(
                            'column' => 'image',
                            'value' => function($entity){
                                return Element::image($entity->getImageUrl('400x400'), array('class' => 'img-responsive center-block'));                                
                            }
                        ),
                        array(
                            'column' => 'order'
                        )
                    ),
                    'actions' => array(
                        'edit' => function($entity){
                            return Element::icon('glyphicon glyphicon-pencil', $this->url('Tour:Admin:TourGallery@editAction', $entity['id']));
                        },
                        'delete' => function($entity){
                            // Generate URL
                            $url = $this->url('Tour:Admin:TourGallery@deleteAction', $entity['id']);
                            return Element::icon('glyphicon glyphicon-remove', '#', array('data-button' => 'delete', 'data-url' => $url));
                        }
                    )
                ), $this->translator); ?>
            </div>
        </div>
        
	</div>
</form>
