<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form data-group="image">
    <div class="well">
        <?php echo Element::hidden('image[id]', $image->getId()); ?>
        <?php echo Element::hidden('image[image]', $image->getImage()); ?>
        <?php echo Element::hidden('image[tour_id]', $image->getTourId()); ?>

        <div class="form-group">
            <label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
            <div class="col-lg-10">
                <p>
                    <img data-image="<?php echo $image->getId() ? null : 'preview'; ?>" src="<?php echo $image->getImageUrl('400x400'); ?>" />
                </p>

                <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
            </div>
        </div>

		<div class="form-group">
			<label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
			<div class="col-lg-10">
				<div class="input-group">
                    <?php echo Element::text('image[order]', $image->getOrder(), array('class' => 'form-control', 'placeholder' => $this->translate('Sorting order'))); ?>
					<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
				</div>
			</div>
		</div>
	</div>

    <?php if ($image->getId()):?>

    <button data-button="save" data-url="<?php echo $this->url('Tour:Admin:TourGallery@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
    <button data-button="save-create" data-back-url="<?php echo $this->url('Tour:Admin:TourGallery@addAction'); ?>" data-url="<?php echo $this->url('Tour:Admin:TourGallery@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save & Create new'); ?></button>
    <?php else: ?>

    <button data-button="add" data-back-url="<?php echo $this->url('Tour:Admin:TourGallery@editAction', null); ?>" data-url="<?php echo $this->url('Tour:Admin:TourGallery@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php echo $this->translate('Add'); ?></button>
    <button data-button="add-create" data-url="<?php echo $this->url('Tour:Admin:TourGallery@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php echo $this->translate('Add & Create new'); ?></button>
    <?php endif; ?>

    <button data-button="cancel" data-url="<?php echo $this->url('Tour:Admin:TourGallery@indexAction', null); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
