<?php

use Krystal\Form\Element;

?>

<form class="card card-body" autocomplete="off">
    <?= Element::hidden('policy[id]', $policy->getId()); ?>
    <?= Element::hidden('policy[tour_id]', $policy->getTourId()); ?>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Number of people'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('policy[qty]', $policy->getQty(), ['class' => 'form-control']); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Price'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('policy[price]', $policy->getPrice(), ['class' => 'form-control']); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$policy->getId(),
        'add' => ['Tour:Admin:TourPricePolicy@addAction', $policy->getTourId()],
        'edit' => 'Tour:Admin:TourPricePolicy@editAction',
        'save' => 'Tour:Admin:TourPricePolicy@saveAction',
        'cancel' => ['Tour:Admin:Tour@editAction', $policy->getTourId()]
    ]); ?>

</form>