<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

?>

<form class="card" autocomplete="off">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" href="#page" data-bs-toggle="tab"><i class="fas fa-calendar-day"></i> <?= $this->translate('Tour day'); ?></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#configuration" data-bs-toggle="tab"><i class="fas fa-tasks"></i> <?= $this->translate('Configuration'); ?></a>
        </li>
    </ul>

    <div class="tab-content pt-3">
        <div class="tab-pane fade show active" id="page">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade <?= $index == 0 ? 'show active' : null; ?>" id="<?= sprintf('language-%s', $language->getId()); ?>">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $day); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Title'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'placeholder' => $this->translate('Category name')]); ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['data-wysiwyg' => 'true']); ?>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>

            <?php $this->loadPartial('actions', [
                'new' => !$entity->getId(),
                'add' => ['Tour:Admin:TourDay@addAction', $entity->getTourId()],
                'edit' => 'Tour:Admin:TourDay@editAction',
                'save' => 'Tour:Admin:TourDay@saveAction',
                'cancel' => ['Tour:Admin:Tour@editAction', $entity->getTourId()]
            ]); ?>
		</div>

        <div class="tab-pane fade" id="configuration">
            <?= Element::hidden('day[id]', $entity->getId()) ?>
            <?= Element::hidden('day[tour_id]', $entity->getTourId()) ?>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Order'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::number('day[order]', $entity->getOrder(), ['class' => 'form-control', 'min' => 0]) ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Time'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::time('day[time]', $entity->getTime(), ['class' => 'form-control']) ?>
                        <span class="input-group-text"><i class="bi bi-clock"></i></span>
                    </div>
                </div>
            </div>
        </div>
	</div>
</form>