<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="date" autocomplete="off">
    <?= Element::hidden('date[id]', $date->getId()); ?>
    <?= Element::hidden('date[tour_id]', $date->getTourId()); ?>

    <div class="form-group row">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Start date'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('date[start]', $date->getStart(), ['class' => 'form-control', 'data-plugin' => 'datepicker', 'placeholder' => $this->translate('Start date')]); ?>
                <div class="input-group-append">
                    <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group row">
        <label class="col-lg-2 col-form-label"><?= $this->translate('End date'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('date[end]', $date->getEnd(), ['class' => 'form-control', 'data-plugin' => 'datepicker', 'placeholder' => $this->translate('End date')]); ?>
                <div class="input-group-append">
                    <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$date->getId(),
        'add' => ['Tour:Admin:TourDate@addAction', $date->getTourId()],
        'edit' => 'Tour:Admin:TourDate@editAction',
        'save' => 'Tour:Admin:TourDate@saveAction',
        'cancel' => ['Tour:Admin:Tour@editAction', $date->getTourId()]
    ]); ?>
</form>