<?php

use Cms\Service\LanguageManager;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="day" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#page" role="tab" data-toggle="tab"><i class="fas fa-calendar-day"></i> <?php $this->show('Tour day'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="fas fa-tasks"></i> <?php $this->show('Configuration'); ?></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade in <?= $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $day); ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <?= $this->field()->hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= $this->field()->hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                    <?= $this->field('Title')->text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'placeholder' => $this->translate('Category name')]); ?>
                    <?= $this->field('Description')->textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['data-wysiwyg' => 'true']); ?>
                </div>
                <?php endforeach; ?>
            </div>

            <?php $this->loadPartial('actions', [
                'new' => !$entity->getId(),
                'add' => ['Tour:Admin:TourDay@addAction', $entity->getTourId()],
                'edit' => 'Tour:Admin:TourDay@editAction',
                'save' => 'Tour:Admin:TourDay@saveAction',
                'cancel' => ['Tour:Admin:Tour@editAction', $entity->getTourId()]
            ]); ?>
		</div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <?= $this->field()->hidden('day[id]', $entity->getId()) ?>
            <?= $this->field()->hidden('day[tour_id]', $entity->getTourId()) ?>
            <?= $this->field('Order')->number('day[order]', $entity->getOrder(), ['class' => 'form-control', 'min' => 0]) ?>
            <?= $this->field('Time')->time('day[time]', $entity->getTime(), ['class' => 'form-control']) ?>
        </div>
	</div>
</form>
