<?php

use Krystal\Form\Element;
use Krystal\Widget\GridWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php if (empty($categories)): ?>

<div class="alert alert-dismissible alert-danger">
    <p><?php $this->show('Error occurred'); ?>!</p>
    <strong><?php $this->show('You have no categories to attach tours'); ?>.</strong> <?php $this->show('Please add at least one category'); ?>.
</div>

<?php else: ?>

<form data-group="tour" novalidate autocomplete="off">
	<ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Tour'); ?></a></li>
        <?php if (!$new): ?>
        <li role="presentation"><a href="#days" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-time"></i> <?php $this->show('Days'); ?></a></li>
        <li role="presentation"><a href="#dates" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-calendar"></i> <?php $this->show('Dates'); ?></a></li>
        <li role="presentation"><a href="#gallery" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-camera"></i> <?php $this->show('Gallery'); ?></a></li>
        <li role="presentation"><a href="#reviews" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-comment"></i> <?php $this->show('Reviews'); ?> (<?= count($reviews); ?>)</a></li>
        <?php endif; ?>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-check"></i> <?php $this->show('Configuration'); ?></a></li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="page" role="tabpanel">
            <div class="well">
                <?php $this->loadPartial('language-tabs'); ?>

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                        <?php $entity = LanguageManager::findByLangId($language->getId(), $tour); ?>

                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('What\'s included'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][included]', $language->getId()), $entity->getIncluded(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('What\'s not included'); ?></label>
                            <div class="col-lg-10">
                                <?php echo Element::textarea(sprintf('translation[%s][excluded]', $language->getId()), $entity->getExcluded(), array('data-wysiwyg' => 'true')); ?>
                            </div>
                        </div>

                        <div class="options">
                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Slug'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), array('class' => 'form-control', 'data-input' => 'slug', 'placeholder' => $this->translate('URL slug for this category. By default is taken from a title'))); ?>
                                        <span class="input-group-addon">
                                            <a href="#" data-button="slug"><i class="glyphicon glyphicon-refresh" data-toggle="tooltip" title="<?php $this->show('Refresh the slug'); ?>"></i></a>
                                        </span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Title'); ?></label>
                                <div class="col-lg-10">
                                    <div class="input-group">
                                        <?php echo Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), array('class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate("Category title"))); ?>
                                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Keywords'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][meta_keywords]', $language->getId()), $entity->getMetaKeywords(), array('class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines'))); ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-lg-2 control-label"><?php $this->show('Description'); ?></label>
                                <div class="col-lg-10">
                                    <?php echo Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), array('class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines'))); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
			</div>

            <?php $this->loadPartial('actions', array(
                'new' => !$entity->getId(),
                'add' => 'Tour:Admin:Tour@addAction',
                'edit' => 'Tour:Admin:Tour@editAction',
                'save' => 'Tour:Admin:Tour@saveAction',
                'cancel' => 'Tour:Admin:Grid@indexAction',
                'options' => true
            )); ?>

		</div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <div class="well">
                <?php echo Element::hidden('tour[id]', $entity->getId()); ?>
                <?php echo Element::hidden('tour[cover]', $entity->getCover()); ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Image'); ?></label>
                    <div class="col-lg-10">
                        <p>
                            <img data-image="<?php echo $entity->getId() ? null : 'preview'; ?>" src="<?php echo $entity->getImageUrl('400x400'); ?>" />
                        </p>

                        <a class="btn btn-primary" data-button="upload" data-target="[name='file']" href="#"><i class="glyphicon glyphicon-picture"></i> <?php $this->show('Upload a file'); ?></a>
                        <?php echo Element::file('file', 'image/x-png, image/gif, image/jpeg', array('class' => 'hidden', 'data-plugin' => 'preview')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Categories'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('categories[]', $categories, $entity->getCategoryIds(), array('class' => 'form-control', 'multiple' => true, 'data-plugin' => 'chosen')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Related tours'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('related[]', $tours, $entity->getRelatedIds(), array('class' => 'form-control', 'multiple' => true, 'data-plugin' => 'chosen')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Enable SEO'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('tour[seo]', $entity->getSeo(), array('class' => 'form-control')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Recommended'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('tour[recommended]', $entity->getRecommended(), array('class' => 'form-control')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Published'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::checkbox('tour[published]', $entity->getPublished(), array('class' => 'form-control')) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Tour destination'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::select('tour[destination_id]', $destinations, $entity->getDestinationId(), array('class' => 'form-control'), '') ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Price'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[price]', $entity->getPrice(), array('class' => 'form-control', 'min' => 1)) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Start price'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[start_price]', $entity->getStartPrice(), array('class' => 'form-control', 'min' => 1)) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Order'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[order]', $entity->getOrder(), array('class' => 'form-control', 'min' => 0)) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Number of adults'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[adults]', $entity->getAdults(), array('class' => 'form-control', 'min' => 0)) ?>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Number of children'); ?></label>
                    <div class="col-lg-10">
                        <?php echo Element::number('tour[children]', $entity->getChildren(), array('class' => 'form-control', 'min' => 0)) ?>
                    </div>
                </div>
            </div>
        </div>
        
        <div role="tabpanel" class="tab-pane" id="days">
            <h2 class="page-header"><i class="glyphicon glyphicon-time"></i> <?php $this->show('Days'); ?> <small>(<?= count($days); ?>)</small></h2>

            <p>
                <a class="btn btn-primary" href="<?php echo $this->url('Tour:Admin:TourDay@addAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-retweet"></i> <?php $this->show('Add new day'); ?></a>
            </p>

            <?= $this->widget(new GridWidget($days, array(
                'pk' => 'id',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),
                    array(
                        'column' => 'title'
                    ),
                    array(
                        'column' => 'order'
                    )
                ),
                'actions' => array(
                    'edit' => function($entity){
                        return Element::icon('glyphicon glyphicon-pencil', $this->url('Tour:Admin:TourDay@editAction', $entity['id']));
                    },
                    'delete' => function($entity){
                        // Generate URL
                        $url = $this->url('Tour:Admin:TourDay@deleteAction', $entity['id']);
                        return Element::icon('glyphicon glyphicon-remove', '#', array('data-button' => 'delete', 'data-url' => $url));
                    }
                )

            ))); ?>
        </div>
        
        <div role="tabpanel" class="tab-pane" id="dates">
            <h2 class="page-header"><i class="glyphicon glyphicon-calendar"></i> <?php $this->show('Dates'); ?> <small>(<?= count($dates); ?>)</small></h2>

            <p>
                <a class="btn btn-primary" href="<?php echo $this->url('Tour:Admin:TourDate@addAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-retweet"></i> <?php $this->show('Add new date'); ?></a>
            </p>

            <?= $this->widget(new GridWidget($dates, array(
                'pk' => 'id',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),
                    array(
                        'column' => 'start',
                        'label' => 'Start date'
                    ),
                    array(
                        'column' => 'end',
                        'label' => 'End date'
                    )
                ),

                'actions' => array(
                    'edit' => function($entity){
                        return Icon::edit($this->url('Tour:Admin:TourDate@editAction', $entity['id']), $this->translate('Edit this date'));
                    },

                    'delete' => function($entity){
                        return Icon::remove($this->url('Tour:Admin:TourDate@deleteAction', $entity['id']), $this->translate('Remove this date'));
                    }
                )

            ))); ?>
        </div>
        
        <div role="tabpanel" class="tab-pane" id="gallery">
            <h2 class="page-header"><i class="glyphicon glyphicon-camera"></i> <?php $this->show('Gallery'); ?> <small>(<?= count($gallery); ?>)</small></h2>

            <p>
                <a class="btn btn-primary" href="<?php echo $this->url('Tour:Admin:TourGallery@addAction', $entity->getId()); ?>"><i class="glyphicon glyphicon-retweet"></i> <?php $this->show('Add new image'); ?></a>
            </p>

            <?= $this->widget(new GridWidget($gallery, array(
                'pk' => 'id',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),
                    array(
                        'column' => 'image',
                        'value' => function($entity){
                            return Element::image($entity->getImageUrl('400x400'), array('class' => 'img-responsive center-block'));                                
                        }
                    ),
                    array(
                        'column' => 'order'
                    )
                ),

                'actions' => array(
                    'edit' => function($entity){
                        return Icon::edit($this->url('Tour:Admin:TourGallery@editAction', $entity['id']), $this->translate('Edit this image'));
                    },
                    'remove' => function($entity){
                        return Icon::remove($this->url('Tour:Admin:TourGallery@deleteAction', $entity['id']), $this->translate('Remove this image'));
                    }
                )

            ))); ?>

        </div>

        <div role="tabpanel" class="tab-pane" id="reviews">
            <h2 class="page-header"><i class="glyphicon glyphicon-comment"></i> <?php $this->show('Reviews'); ?> <small>(<?= count($reviews); ?>)</small></h2>

            <?= $this->widget(new GridWidget($reviews, array(
                'pk' => 'id',
                'rowAttributes' => array(
                    'class' => function($row){
                        if ($row['published'] == 0){
                            return 'danger';
                        }
                    }
                ),
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#'
                    ),

                    array(
                        'column' => 'datetime',
                        'label' => 'Date and time'
                    ),

                    array(
                        'column' => 'name'
                    ),

                    array(
                        'column' => 'message'
                    )
                ),

                'actions' => array(
                    'approve' => function($entity){
                        if ($entity['published'] == 0){
                            $url = $this->url('Tour:Admin:TourReview@approveAction', $entity['id']);
                            return Icon::button('glyphicon glyphicon-check', $url, $this->translate('Approve this review'));
                        }
                    },

                    'remove' => function($entity){
                        return Icon::remove(
                            $this->url('Tour:Admin:TourReview@deleteAction', $entity['id']),
                            $this->translate('Remove this review')
                        );
                    }
                )

            ))); ?>
        </div>
	</div>
</form>

<?php endif; ?>
