<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="date" autocomplete="off">
    <?php echo Element::hidden('date[id]', $date->getId()); ?>
    <?php echo Element::hidden('date[tour_id]', $date->getTourId()); ?>

    <div class="form-group">
        <label class="col-lg-2 control-label"><?php $this->show('Start date'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?php echo Element::text('date[start]', $date->getStart(), array('class' => 'form-control', 'data-plugin' => 'datepicker', 'placeholder' => $this->translate('Start date'))); ?>
                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-2 control-label"><?php $this->show('End date'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?php echo Element::text('date[end]', $date->getEnd(), array('class' => 'form-control', 'data-plugin' => 'datepicker', 'placeholder' => $this->translate('End date'))); ?>
                <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$date->getId(),
        'add' => array('Tour:Admin:TourDate@addAction', $date->getTourId()),
        'edit' => 'Tour:Admin:TourDate@editAction',
        'save' => 'Tour:Admin:TourDate@saveAction',
        'cancel' => array('Tour:Admin:Tour@editAction', $date->getTourId())
    )); ?>

</form>
