<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="btn-toolbar">
    <a class="btn btn-primary btn-sm" href="<?= $this->url('Tour:Admin:TourDestination@addAction'); ?>"><i class="bi bi-arrows-angle-contract"></i> <?= $this->translate('Add new tour destination'); ?></a>
</div>

<div class="card">
    <h2 class="page-header"><i class="bi bi-arrows-angle-contract"></i> <?= $this->translate('Tour destinations'); ?> <small>(<?= count($destinations); ?>)</small></h2>

    <?= $this->widget(new GridViewWidget($destinations, [
        'pk' => 'id',
        'tableClass' => 'table table-hover table-bordered table-striped',
        'columns' => [
            [
                'column' => 'id',
                'label' => '#'
            ],

            [
                'column' => 'name',
            ],

            [
                'column' => 'order',
            ]
        ],

        'actions' => [
            function($row){
                return Icon::edit(
                    $this->url('Tour:Admin:TourDestination@editAction', $row['id']),
                    $this->translate('Edit this destination')
                );
            },

            function($row){
                return Icon::remove(
                    $this->url('Tour:Admin:TourDestination@deleteAction', $row['id']),
                    $this->translate('Remove this destination')
                );
            }
        ]
    ])); ?>

    <?php if (empty($destinations)): ?>
    <h2 class="text-center text-muted"><i class="bi bi-x"></i> <?= $this->translate('No tour destinations'); ?></h2>
    <?php endif; ?>

</div>