<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="date" autocomplete="off">
    <?= $this->field()->hidden('date[id]', $date->getId()); ?>
    <?= $this->field()->hidden('date[tour_id]', $date->getTourId()); ?>
    <?= $this->field('Start date')->text('date[start]', $date->getStart(), ['class' => 'form-control', 'data-plugin' => 'datepicker', 'placeholder' => $this->translate('Start date')]); ?>
    <?= $this->field('End date')->text('date[end]', $date->getEnd(), ['class' => 'form-control', 'data-plugin' => 'datepicker', 'placeholder' => $this->translate('End date')]); ?>

    <?php $this->loadPartial('actions', [
        'new' => !$date->getId(),
        'add' => ['Tour:Admin:TourDate@addAction', $date->getTourId()],
        'edit' => 'Tour:Admin:TourDate@editAction',
        'save' => 'Tour:Admin:TourDate@saveAction',
        'cancel' => ['Tour:Admin:Tour@editAction', $date->getTourId()]
    ]); ?>
</form>