<?php

defined('KRYSTAL') or die;

?>

<form class="card" data-group="booking" autocomplete="off">
    <?= $this->field()->hidden('booking[id]', $booking->getId());?>
    <?= $this->field()->hidden('booking[token]', $booking->getToken());?>

    <?= $this->field('Tour')->text('booking[tour]', $booking->getTour(), ['class' => 'form-control', 'placeholder' => $this->translate('Tour name')]);?>
    <?= $this->field('Client')->text('booking[tour]', $booking->getClient(), ['class' => 'form-control', 'placeholder' => $this->translate('Client name')]);?>
    <?= $this->field('Email')->text('booking[tour]', $booking->getEmail(), ['class' => 'form-control', 'placeholder' => $this->translate('Client email')]);?>
    <?= $this->field('Phone')->text('booking[tour]', $booking->getPhone(), ['class' => 'form-control', 'placeholder' => $this->translate('Client phone')]);?>
    <?= $this->field('Amount')->text('booking[tour]', $booking->getAmount(), ['class' => 'form-control', 'placeholder' => $this->translate('Amount to be charged')]);?>

    <?php $this->loadPartial('actions', [
        'new' => !$booking->getId(),
        'add' => 'Tour:Admin:Booking@addAction',
        'edit' => 'Tour:Admin:Booking@editAction',
        'save' => 'Tour:Admin:Booking@saveAction',
        'cancel' => ['Tour:Admin:Booking@indexAction', null]
    ]); ?>
</form>