<?php

use Krystal\Form\Element;

?>

<form class="card card-body" autocomplete="off">
    <?= Element::hidden('booking[id]', $booking->getId()); ?>
    <?= Element::hidden('booking[token]', $booking->getToken()); ?>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Tour'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('booking[tour]', $booking->getTour(), ['class' => 'form-control', 'placeholder' => $this->translate('Tour name')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Client'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('booking[client]', $booking->getClient(), ['class' => 'form-control', 'placeholder' => $this->translate('Client name')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Email'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('booking[email]', $booking->getEmail(), ['class' => 'form-control', 'placeholder' => $this->translate('Client email')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Phone'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('booking[phone]', $booking->getPhone(), ['class' => 'form-control', 'placeholder' => $this->translate('Client phone')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <div class="row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Amount'); ?></label>
        <div class="col-lg-10">
            <div class="input-group">
                <?= Element::text('booking[amount]', $booking->getAmount(), ['class' => 'form-control', 'placeholder' => $this->translate('Amount to be charged')]); ?>
                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$booking->getId(),
        'add' => 'Tour:Admin:Booking@addAction',
        'edit' => 'Tour:Admin:Booking@editAction',
        'save' => 'Tour:Admin:Booking@saveAction',
        'cancel' => ['Tour:Admin:Booking@indexAction', null]
    ]); ?>
</form>