<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Cms\View\Icon;

?>

<div class="btn-toolbar mb-3">
    <?php $this->loadPartial('menu', [
        'items' => [
            'Tour:Admin:Booking@addAction' => 'New booking'
        ],
        'actions' => [
            'data' => $bookings,
            'delete' => 'Tour:Admin:Booking@deleteAction'
        ]
    ]); ?>
</div>

<div class="card">
    <?php $this->loadPartial('items-per-page', ['caption' => 'Bookings']); ?>

    <form autocomplete="off">
        <?= $this->widget(new GridViewWidget($bookings, [
            // A column to be considered as a primary key
            'pk' => 'id',
            'batch' => true,
            'tableClass' => 'table table-hover table-bordered table-striped table-sm',
            'rowAttributes' => [
                'class' => function($row){
                    if ($row['status'] == -1) {
                        return 'table-danger';
                    }
                }
            ],

            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'start'
                ],

                [
                    'column' => 'end'
                ],

                [
                    'column' => 'tour',
                ],

                [
                    'column' => 'client',
                ],

                [
                    'column' => 'email',
                ],

                [
                    'column' => 'phone',
                ],
                
                [
                    'column' => 'datetime',
                    'label' => 'Date and time'
                ],

                [
                    'column' => 'amount',
                    'label' => 'Price'
                ]
            ],

            'actions' => [
                function($row){
                    // Don't let
                    if ($row['amount'] == 0) {
                        return null;
                    }

                    return Icon::button('fas fa-envelope', $this->url('Tour:Admin:Booking@notifyAction', $row['token']), $this->translate('Send invoice to their email'));
                },

                function($row){
                    return Icon::edit(
                        $this->url('Tour:Admin:Booking@editAction', $row['id']),
                        $this->translate('Edit this booking')
                    );
                },

                function($row){
                    return Icon::remove(
                        $this->url('Tour:Admin:Booking@deleteAction', $row['id']),
                        $this->translate('Delete this booking')
                    );
                }
            ]
        ])); ?>
    </form>

    <?php $this->loadPartial('paginator'); ?>
</div>